# Generated by Django 4.1.5 on 2023-01-31 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupevents',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 19, 51, 19, 37799)),
        ),
    ]
