# Generated by Django 4.1.5 on 2023-01-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groupadditionaldetailsmodel_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupadditionaldetailsmodel',
            name='username_to_be_added',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupadditionaldetailsmodel',
            name='image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
