# Generated by Django 4.1.5 on 2023-01-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_groupadditionaldetailsmodel_username_to_be_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupadditionaldetailsmodel',
            name='username_to_be_added',
            field=models.CharField(default='malt', max_length=80),
        ),
    ]
