# Generated by Django 4.1.5 on 2023-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_groupadditionaldetailsmodel_username_to_be_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupadditionaldetailsmodel',
            name='username_to_be_added',
            field=models.CharField(default='malt', max_length=80, null=True),
        ),
    ]
