# Generated by Django 4.1.5 on 2023-01-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_groupadditionaldetailsmodel_username_to_be_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupadditionaldetailsmodel',
            name='username_to_be_added',
        ),
    ]
