# Generated by Django 4.1.5 on 2023-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_groupadditionaldetailsmodel_username_to_be_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadGroupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='group_thumbs/')),
                ('username_to_be_added', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupadditionaldetailsmodel',
            name='uploaded_image',
        ),
        migrations.RemoveField(
            model_name='groupadditionaldetailsmodel',
            name='username_to_be_added',
        ),
    ]
