# Generated by Django 4.1.5 on 2023-01-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_uploadgroupdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupadditionaldetailsmodel',
            name='members',
        ),
    ]
