# Generated by Django 4.1.5 on 2023-01-26 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0013_remove_groupadditionaldetailsmodel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupadditionaldetailsmodel',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
