# Generated by Django 4.1.5 on 2023-01-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermediadetails_delete_uploadimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediadetails',
            name='local_img_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
