# Generated by Django 4.1.5 on 2023-01-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermediadetails_local_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediadetails',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
