# Generated by Django 4.1.5 on 2023-01-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usermediadetails_local_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediadetails',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
